services:
  shelly-exporter:
    ports:
      - 8000:8000
    container_name: shelly-exporter
    environment:
      - SHELLY_HOSTS=192.168.xx.xx,192.168.xx.xx
      - POLL_INTERVAL=5
      - PORT=8000
    image: sparklingsausage/shelly-prometheus:latest
